name: Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Install dependencies
      run: |
        go mod download
        go install gotest.tools/gotestsum@latest
    - name: Build
      run: go build -v ./...
    - name: Run unit tests
      run: gotestsum --format pkgname --junitfile unit-tests.xml -- -tags=unit ./...
    - name: Run integration tests
      run: gotestsum --format pkgname --junitfile integration-tests.xml -- -tags=integration ./tests/integration/...
    - name: Build Docker image
      run: docker build --target app -t url-shortener .
    - name: Archive test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          unit-tests.xml
          integration-tests.xml